version: '2'
services:
  cvdtc-postgres:
    build: postgres
    ports: 
     - "5434:5432"
    environment:
     -  POSTGRES_PASSWORD=chouette
     -  POSTGRES_USER=chouette
    volumes:
     - ./data/postgresql:/var/lib/postgresql/data
  cvdtc-iev:
    build: iev
    ports:
     - "8082:8080"
     - "9992:9990"
    volumes:
     - ./data/referentials:/opt/jboss/referentials
    links:
     - cvdtc-postgres:cvdtc-postgres

